In [23]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import benji_utils as utils
import bbbfs_algorithms as bbbfa

import networkit as nk
import pandas as pd

df = utils.df

In [24]:
import importlib
importlib.reload(bbbfa)

<module 'bbbfs_algorithms' from '/Users/benjidayan/coding/external-validity/benji/bbbfs_algorithms.py'>

In [25]:
importlib.reload(utils)
utils.input_names_real[:10]
utils.input_names_real_with_cl[:10]
gnames = utils.input_names_real_with_cl

<module 'benji_utils' from '/Users/benjidayan/coding/external-validity/benji/benji_utils.py'>

['08blocks',
 '1138_bus',
 '130bit',
 '145bit',
 '162bit',
 '176bit',
 '192bit',
 '208bit',
 '2D_27628_bjtcai',
 '2D_54019_highK']

['130bit',
 '145bit',
 '162bit',
 '176bit',
 '192bit',
 '208bit',
 '2D_27628_bjtcai',
 '2D_54019_highK',
 '2cubes_sphere',
 '3D_28984_Tetra']

In [27]:
import os
os.listdir(utils.p)

['.DS_Store',
 'real_fake_output',
 'edge_list',
 'output_data',
 'edge_list_cl2',
 'edge_list_cl',
 'real_fake_output.zip',
 'cl_fake.zip']

In [32]:
outnames = os.listdir(utils.p + '/real_fake_output')
outnames = [x[:-4] for x in outnames]
set(utils.input_names_real_with_cl) - set(outnames)

{'qa8fk',
 'struct3',
 'ted_AB',
 'thermal1',
 'thermomech_dM',
 'torso2',
 'trdheim',
 'tube1',
 'turon_m',
 'wathen100',
 'wathen120',
 'waveguide3D',
 'wb-cs-stanford',
 'web-edu',
 'web-indochina-2004',
 'web-polblogs',
 'web-sk-2005',
 'web-spam',
 'web-spam-detection',
 'webkb-wisc',
 'wing_nodal'}

In [22]:
gname = gnames[7]
g = utils.graph_name_to_nk(gname)
# print(g.numberOfNodes(), g.numberOfEdges())
bbbfa.do_real_fake_comparison(gnames[0], n_pairs=500)

nodes: 584 584 edges: 6058 5962


s    t                                    algo  search_space  dist  \
0     166  181  python-BiBFS_VertexBalancedApproximate            17     2   
1     215  293  python-BiBFS_VertexBalancedApproximate            13     2   
2     129  299  python-BiBFS_VertexBalancedApproximate            26     2   
3     129  546  python-BiBFS_VertexBalancedApproximate            32     2   
4      71  285  python-BiBFS_VertexBalancedApproximate            22     2   
...   ...  ...                                     ...           ...   ...   
3995  160  245    python-BiBFS_EdgeBalancedApproximate            11     2   
3996   70  190    python-BiBFS_EdgeBalancedApproximate             2     2   
3997  271  518    python-BiBFS_EdgeBalancedApproximate             9     2   
3998   17  458    python-BiBFS_EdgeBalancedApproximate            11     2   
3999  128  545    python-BiBFS_EdgeBalancedApproximate            12     2   

      time_dist   graph  
0      0.000049  130bit  
1      0.000012  130bit  
2      0.000018  130bit  
3      0.000019  130bit  
4      0.000014  130bit  
...         ...     ...  
3995   0.000029  130bit  
3996   0.000017  130bit  
3997   0.000022  130bit  
3998   0.000035  130bit  
3999   0.000030  130bit  

[4000 rows x 7 columns]

In [5]:
importlib.reload(utils)
utils.check_cls()

<module 'benji_utils' from '/Users/benjidayan/coding/external-validity/benji/benji_utils.py'>

No cl graph for 08blocks
No cl graph for 1138_bus
130bit 584 584       6058 5962
145bit 1002 1002       11251 11281
162bit 3606 3606       37069 36792
176bit 7441 7441       82204 81719
192bit 13691 13689       154235 154098
208bit 24430 24426       299684 299614
2D_27628_bjtcai 27628 27605       207723 207529
2D_54019_highK 54019 53996       472098 471131
2cubes_sphere 101492 101378       772886 773528
3D_28984_Tetra 28984 28976       288684 289756
3elt 4720 4484       13722 13746
No cl graph for 494_bus
598a 110971 110681       741934 742545
No cl graph for 662_bus
685_bus 685 689       1282 1239
ABACUS_shell_hd 23412 22975       97536 97193
No cl graph for AIDS
ASIC_100k 99340 97753       427449 428806


In [22]:
df = bbbfa.do_comparison2('192bit')

n2=13691, e2=154235, n_act=13690, e_act=153974
n2=13692, e2=154485.1578930725, n_act=13692, e_act=154769
n2=13691, e2=153963.38200380106, n_act=13689, e_act=153220
nodes: 13691 13689 edges: 154235 153220


In [254]:
import generators
importlib.reload(generators)

weights = powerlaw_dist(2.5, 1, 20)
weights = weights / np.sqrt(weights.sum())
edge_probs = generators.chung_lu_generate(weights, 1, graph=False)
edge_probs
weights

g = utils.graph_name_to_nk('176bit')
n, e = g.numberOfNodes(), g.numberOfEdges()
n, e

g_cl = generators.fit_connected_chunglu_to_g(g, tau=2.5, iters=5, tol=0.1)
weights = powerlaw_dist(2.5, 1, n)
weights = weights / np.sqrt(weights.sum())


# _, g_cl2 = generators.chung_lu_fit_c_lite2(g, weights, do_print=True)
# g_cl2.numberOfNodes(), g_cl2.numberOfEdges()

<module 'generators' from '/Users/benjidayan/coding/external-validity/benji/generators.py'>

20.180868348244104

array([0.15485751, 0.16759399, 0.17089168, 0.16909331, 0.17704061,
       0.40427963, 0.15943969, 0.36484778, 0.20777969, 0.32600491,
       0.15561163, 0.44006404, 0.2473533 , 0.35298474, 0.16830394,
       1.39175654, 0.18605786, 0.74233107, 0.22868559, 0.43617632])

(7441, 82204)

n2=7441, e2=82204, n_act=7437, e_act=82836


In [255]:
g_cl = generators.fit_connected_chunglu_to_g(g, tau=2.5, iters=5, tol=0.1)

n2=7441, e2=82204, n_act=7441, e_act=81735


In [246]:
_, g_cl2 = generators.chung_lu_fit_c_lite2(g, weights, do_print=True)
g_cl2.numberOfNodes(), g_cl2.numberOfEdges()

num_edges=82204, E_edges=81908, c=1133.9736384079824
num_edges=82204, E_edges=82140, c=1138.0716043816208
num_edges=82204, E_edges=82166, c=1138.9583414485849
num_edges=82204, E_edges=81806, c=1139.4850850770326
num_edges=82204, E_edges=82470, c=1145.028872376994


(7441, 82470)

In [234]:
_, g_cl2 = generators.chung_lu_fit_c_lite2(g, weights, do_print=True)
g_cl2.numberOfNodes(), g_cl2.numberOfEdges()

num_edges=6058, E_edges=5939, c=297.1637552782411
num_edges=6058, E_edges=5829, c=303.11803830200114
num_edges=6058, E_edges=6028, c=315.02643267001594
num_edges=6058, E_edges=6300, c=316.5942483601454
num_edges=6058, E_edges=6009, c=304.43300897869216


(584, 6009)

In [201]:
_, g_cl2 = generators.chung_lu_fit_c_lite(g, weights)
g_cl2.numberOfNodes(), g_cl2.numberOfEdges()

(13691, 154110)

In [92]:
weights = np.array([0.8]*20)
g_temp = nk.generators.ChungLuGenerator(weights).generate()
g_temp.numberOfNodes(), g_temp.numberOfEdges()

weights = np.array([0.8]*10 + [1.2]*10)
g_temp = nk.generators.ChungLuGenerator(weights).generate()
g_temp.numberOfNodes(), g_temp.numberOfEdges()

weights = powerlaw_dist(2.5, 1, 10)
weights
g_temp = nk.generators.ChungLuGenerator(weights).generate()
g_temp.numberOfNodes(), g_temp.numberOfEdges()

(20, 0)

(20, 5)

array([ 7.32539205,  1.24789585,  1.20931247,  1.3817054 ,  2.36514547,
       17.54787121,  1.12190679,  9.08680069,  1.86435494,  1.11368978])

(10, 12)

In [ ]:
generators.chung_lu_fit_c_lite2()

In [142]:
weights = np.array([1.9] * 2000)
g_temp = nk.generators.ChungLuGenerator(weights).generate()
g_temp.numberOfNodes(), g_temp.numberOfEdges()

weights = np.array([1.1] * 2000)
g_temp = nk.generators.ChungLuGenerator(weights).generate()
g_temp.numberOfNodes(), g_temp.numberOfEdges()

weights = np.array([1.0] * 2000)
g_temp = nk.generators.ChungLuGenerator(weights).generate()
g_temp.numberOfNodes(), g_temp.numberOfEdges()

weights = np.array([1.0] * 1500 + [2.0]* 500)
g_temp = nk.generators.ChungLuGenerator(weights).generate()
g_temp.numberOfNodes(), g_temp.numberOfEdges()

(2000, 973)

(2000, 943)

(2000, 975)

(2000, 1252)

In [82]:
g_cl = generators.generate_chung_lu(1000, tau=2.5, desiredAvgDegree=50)
g_cl.numberOfEdges()

25284

In [65]:
generators.chung_lu_fit_c(g, weights)

(9.143297119793147,
 array([[0.00758366, 0.02676619, 0.00815251, ..., 0.00855625, 0.00934363,
         0.00921026],
        [0.02676619, 0.09447012, 0.02877394, ..., 0.03019891, 0.03297796,
         0.03250721],
        [0.00815251, 0.02877394, 0.00876404, ..., 0.00919806, 0.01004451,
         0.00990113],
        ...,
        [0.00855625, 0.03019891, 0.00919806, ..., 0.00965358, 0.01054194,
         0.01039146],
        [0.00934363, 0.03297796, 0.01004451, ..., 0.01054194, 0.01151206,
         0.01134773],
        [0.00921026, 0.03250721, 0.00990113, ..., 0.01039146, 0.01134773,
         0.01118574]]))

In [77]:
generators.chung_lu_generate(weights, 9.14, graph=False)
generators.chung_lu_generate(weights, 9.14, graph=True).numberOfEdges()

6056.069676070653

6157

In [79]:
weights = powerlaw_dist(2.5, 1, 25000)
weights = weights / np.sqrt(weights.sum())
generators.chung_lu_generate(weights, 9.14, graph=False)
generators.chung_lu_generate(weights, 9.14, graph=True).numberOfEdges()

328428.8306243524

329613

In [26]:
weights= powerlaw_dist(2.5, 1, 54000)

In [39]:
weights = powerlaw_dist(2.5, 1, 20)
weights = weights / np.sqrt(weights.sum())

In [51]:
i = 1
c = 1
probs_k_to_kpi = np.minimum(c * weights[:-i] * np.roll(weights, -i)[:-i], 1)
ps = np.random.uniform(size=len(probs_k_to_kpi))
ps.shape
ps
np.argwhere(ps < probs_k_to_kpi).flatten()


(19,)

array([0.5716062 , 0.80837403, 0.04771776, 0.29313781, 0.08925896,
       0.82807077, 0.13722305, 0.23939508, 0.977072  , 0.86246797,
       0.53738973, 0.85124675, 0.21729573, 0.70652174, 0.62625577,
       0.9301608 , 0.36429967, 0.04042535, 0.90662747])

array([2, 3, 4])

In [46]:
weights

array([0.1330955 , 0.15830965, 0.15333431, 2.04797458, 0.1935963 ,
       0.92429683, 0.17010311, 0.14892215, 0.22267662, 0.28267547,
       0.13529015, 0.13589154, 0.15647914, 0.1308641 , 1.19879681,
       0.15041275, 0.17994412, 0.27770109, 0.14009894, 0.70399216])

In [45]:
probs_k_to_kpi


array([0.0210703 , 0.0242743 , 0.31402478, 0.39648031, 0.17894045,
       0.15722577, 0.02533212, 0.03316148, 0.06294522, 0.0382432 ,
       0.01838479, 0.02126419, 0.0204775 , 0.15687946, 0.18031432,
       0.02706589, 0.04997068, 0.03890563, 0.09862855])

In [47]:
0.13 * 1.2

0.156

In [36]:
x = np.arange(6)
x
np.roll(x, -1)
x

array([0, 1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5, 0])

array([0, 1, 2, 3, 4, 5])

In [19]:

df

s     t                                    algo  search_space  dist  \
0      524  2769  python-BiBFS_VertexBalancedApproximate            76     2   
1      772  1559  python-BiBFS_VertexBalancedApproximate            31     2   
2      535  3282  python-BiBFS_VertexBalancedApproximate            30     3   
3     6552  6641  python-BiBFS_VertexBalancedApproximate            31     3   
4     2652  4823  python-BiBFS_VertexBalancedApproximate            88     3   
...    ...   ...                                     ...           ...   ...   
1995  4139  4931  python-BiBFS_VertexBalancedApproximate            71     3   
1996  5191  6228  python-BiBFS_VertexBalancedApproximate            43     3   
1997   174   414  python-BiBFS_VertexBalancedApproximate           480     3   
1998   355  5957  python-BiBFS_VertexBalancedApproximate           544     4   
1999    45  5633  python-BiBFS_VertexBalancedApproximate            38     2   

      time_dist   graph  
0      0.000070  176bit  
1      0.000026  176bit  
2      0.000021  176bit  
3      0.000020  176bit  
4      0.000047  176bit  
...         ...     ...  
1995   0.000037  176bit  
1996   0.000024  176bit  
1997   0.000216  176bit  
1998   0.000232  176bit  
1999   0.000021  176bit  

[2000 rows x 7 columns]

In [16]:
utils.input_names_real[:10]

['08blocks',
 '1138_bus',
 '130bit',
 '145bit',
 '162bit',
 '176bit',
 '192bit',
 '208bit',
 '2D_27628_bjtcai',
 '2D_54019_highK']

In [12]:
import generators
importlib.reload(generators)

# weights = generators.powerlaw_dist(2.5, 1, 1000)
# import matplotlib.pyplot as plt
# plt.hist(weights, bins=20)

g = utils.graph_name_to_nk('130bit')
g.numberOfNodes(), g.numberOfEdges()

# g_cl = generators.generate_chung_lu(1000, tau=2.5, desiredAvgDegree=50)
g_cl = generators.fit_connected_chunglu_to_g(g, 2.5, 10)

<module 'generators' from '/Users/benjidayan/coding/external-validity/benji/generators.py'>

(584, 6058)

n2=584, e2=6058, n_act=584, e_act=6098
n2=584, e2=6018.2623811085605, n_act=584, e_act=6107
n2=584, e2=5969.974374448282, n_act=583, e_act=6004
n2=585, e2=6013.353847240448, n_act=585, e_act=6104
n2=584, e2=5978.25620181995, n_act=584, e_act=5889
n2=584, e2=6149.817638075269, n_act=584, e_act=6077
n2=584, e2=6130.58997062037, n_act=584, e_act=6001
n2=584, e2=6188.820870191335, n_act=584, e_act=6188
n2=584, e2=6058.803625019248, n_act=584, e_act=6042
n2=584, e2=6074.848123198709, n_act=584, e_act=6080


In [10]:
1185/1008

1.1755952380952381

In [8]:
g_cl = generators.fit_connected_chunglu_to_g(g, 2.5, iters=15)

n2=1138, e2=1458, n_act=886, e_act=1435
n2=1461, e2=1153.332703012192, n_act=804, e_act=1129
n2=2067, e2=1052.2815975670865, n_act=734, e_act=829
n2=2276, e2=1193.68233460557, n_act=912, e_act=1099
n2=2276, e2=1269.1155768670417, n_act=928, e_act=1093
n2=2276, e2=1380.5249207490326, n_act=1054, e_act=1233
n2=2276, e2=1511.9486688649301, n_act=1068, e_act=1309
n2=2276, e2=1580.46147868482, n_act=1111, e_act=1401
n2=2276, e2=1605.7395362274883, n_act=1098, e_act=1524
n2=2276, e2=1482.2031628184584, n_act=1019, e_act=1278
n2=2276, e2=1514.1410289347848, n_act=987, e_act=1298
n2=2276, e2=1475.1087864827098, n_act=1046, e_act=1432
n2=2276, e2=1380.4731953930332, n_act=973, e_act=1261
n2=2276, e2=1364.7119486119338, n_act=944, e_act=1223
n2=2276, e2=1349.589818387132, n_act=886, e_act=1147


In [32]:
g_cl.numberOfNodes(), g_cl.numberOfEdges()

(1082, 1331)

In [28]:
g_cl2 = bbbfa.get_chunglu(g)
g_cl2.numberOfNodes(), g_cl2.numberOfEdges()
g_cl2 = generators.get_largest_component(g_cl2)
g_cl2.numberOfNodes(), g_cl2.numberOfEdges()

(1138, 1497)

(914, 1479)

In [29]:
generators.powerlaw_fit_graph(g)

5.12549898740932

In [21]:
generators.powerlaw_fit_graph(g_cl)

2.6765828863724317

In [19]:
import numpy as np
weights = generators.powerlaw_dist(2.5, 1, 1000)
weights2 = weights / np.sqrt(np.sum(weights))
# weights = weights2


desired_avg_degree = 50
num_edges = desired_avg_degree * len(weights) / 2

c = 1.0
# triggered will ensure that c goes just small enough so that probs now less than 1
triggered = False
for _ in range(10):
    probs = np.minimum(c * np.outer(weights, weights), 1)
    E_edges = probs.sum() - np.diag(probs).sum()
    E_edges = E_edges / 2
    print(E_edges, c)
    c = c * (num_edges / E_edges)

probs = np.minimum(c * np.outer(weights, weights), 1)


499500.0 1.0
136394.83218790274 0.05005005005005005
31718.89820624057 0.009173743837504633
25358.39640105453 0.0072305032301687375
25019.19745201396 0.00712831276455247
25001.02940405845 0.007122843146971793
25000.05521496015 0.00712254986770218
25000.00296172393 0.007122534136884639
25000.000158866857 0.007122533293085547
25000.0000085216 0.007122533247824168


In [13]:
g = generators.generate_chung_lu(1000, 2.5, 50)
g.numberOfNodes()
g.numberOfEdges()

1000

24873

In [14]:
1000 * 50

50000

In [5]:
# bbbfa.do_comparison2('1138_bus')

In [6]:
df.graph.unique()[:5]
g = utils.graph_name_to_nk('1138_bus')
g.numberOfNodes()
g.numberOfEdges()
g_cl = bbbfa.get_chunglu(g)
g_cl2 = bbbfa.get_largest_component(g_cl)
g_cl2.numberOfNodes()
g_cl2.numberOfEdges()

array(['08blocks', '1138_bus', '130bit', '145bit', '162bit'], dtype=object)

1138

1458

944

1461

In [7]:
import os
import powerlaw
import sys
class HiddenPrints:
    def __enter__(self):
        self._original_stdout = sys.stdout
        sys.stdout = open(os.devnull, 'w')

    def __exit__(self, exc_type, exc_val, exc_tb):
        sys.stdout.close()
        sys.stdout = self._original_stdout

def powerlaw_fit_graph(g):
    dd = sorted(nk.centrality.DegreeCentrality(g).run().scores(), reverse=True)
    with HiddenPrints():
        fit = powerlaw.Fit(dd, discrete=True)
    return fit.power_law.alpha

powerlaw_fit_graph(g)

5.12549898740932

In [5]:
g_cl = bbbfa.get_chunglu(g)
cc = nk.components.ConnectedComponents(g_cl)
cc.run()

In [17]:
type(g_cl)

networkit.graph.Graph

In [16]:
cc.getComponents()[0]

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,


In [19]:
foo = list(cc.getComponentSizes().items())
foo.sort(key=lambda x: x[1], reverse=True)
foo[:5]

[(0, 912), (28, 4), (1, 2), (5, 2), (21, 2)]

In [26]:
import networkx as nx
nodes = cc.getComponents()[28]
nodes

g_restricted = nk.graphtools.subgraphFromNodes(g, nodes)

g_restricted_nx = nk.nxadapter.nk2nx(g_restricted)
g_restricted_nx_relabelled = nx.relabel.convert_node_labels_to_integers(g_restricted_nx, first_label=0, ordering='default')


[511, 951, 1069, 1071]

In [29]:
g_restricted_nx_relabelled.nodes()
g_restricted_nx_relabelled
list(nk.nxadapter.nx2nk(g_restricted_nx_relabelled).iterNodes())

NodeView((0, 1, 2, 3))

[0, 1, 2, 3]

In [23]:
# restrict to nodes
g_restricted = nk.graphtools.subgraphFromNodes(g, nodes)
g_restricted.numberOfNodes()

4

In [24]:
list(g_restricted.iterNodes())

[511, 951, 1069, 1071]

In [25]:
def get_largest_component(g: Graph) -> Graph:
    cc = nk.components.ConnectedComponents(g)
    cc.run()
    foo = list(cc.getComponentSizes().items())
    foo.sort(key=lambda x: x[1], reverse=True)
    nodes = cc.getComponent()foo[0][0]
    g_restricted = nk.graphtools.subgraphFromNodes(g, nodes)

    g_restricted_nx = nk.nxadapter.nk2nx(g_restricted)
    g_restricted_nx_relabelled = nx.relabel.convert_node_labels_to_integers(g_restricted_nx, first_label=0, ordering='default')
    return nk.nxadapter.nx2nk(g_restricted_nx_relabelled)

# reindex nodes from 0
g_restricted = nk.graphtools.renumberNodes(g_restricted)

import networkx as nx
old_graph = nx.Graph()
reindexed_graph = nx.relabel.convert_node_labels_to_integers(old_graph, first_label=0, ordering='default')

AttributeError: type object 'networkit.graphtools.GraphTools' has no attribute 'renumberNodes'

In [37]:
# gcl = bbbfa.get_chunglu(g)
# gcl.numberOfNodes()
# gcl.numberOfEdges()

temps = []
for g in df.graph.unique()[:40]:
    print(g)
    g = utils.graph_name_to_nk(g)
    nk.setSeed(42, True)
    gcl = bbbfa.get_chunglu(g)
    temps.append((g.numberOfNodes(), gcl.numberOfNodes(), g.numberOfEdges(), gcl.numberOfEdges()))


08blocks
1138_bus
130bit
145bit
162bit
176bit
192bit
208bit
2D_27628_bjtcai
2D_54019_highK
2cubes_sphere
3D_28984_Tetra
3elt
494_bus
598a
662_bus
685_bus
ABACUS_shell_hd
AIDS
ASIC_100k
ASIC_100ks
Alemdar
Andrews
BA-1_10_60-L5
BA-2_24_60-L2
BZR-MD
BZR
C1000-9
C125-9
C2000-5
C250-9
C500-9
CAG_mat1916
CAG_mat364
CAG_mat72
CL-100K-1d8-L9
CL-10K-1d8-L5
COIL-DEL
COIL-RAG
COX2-MD


In [44]:
g.numberOfEdges()
g.numberOfNodes()

630

36

In [45]:
import random
n = g.numberOfNodes()
pairs = random.sample(range(n), 2000)

ValueError: Sample larger than population or is negative

In [41]:
list(filter(lambda x: x[0] == 'g', utils.graph_names))

['g3rmt3m3',
 'g7jac010',
 'g7jac020',
 'g7jac040',
 'g7jac050sc',
 'g7jac060',
 'g7jac080',
 'g7jac100',
 'g7jac120',
 'g7jac140',
 'g7jac160',
 'g7jac180',
 'g7jac200',
 'gams10a',
 'gams30a',
 'gams60am',
 'garon1',
 'garon2',
 'gas11',
 'gas_sensor',
 'ge',
 'gemat1',
 'gemat11',
 'gemat12',
 'gen',
 'gen2',
 'gen200-p0-9-44',
 'gen200-p0-9-55',
 'gen4',
 'gen400-p0-9-55',
 'gen400-p0-9-65',
 'gen400-p0-9-75',
 'gene',
 'gent113',
 'geom',
 'girg_deg_scaling_n=50000_deg=10_dim=2_ple=5.1_T=0.62_seed=1000',
 'girg_deg_scaling_n=50000_deg=10_dim=2_ple=5.1_T=0.62_seed=1001',
 'girg_deg_scaling_n=50000_deg=10_dim=2_ple=5.1_T=0.62_seed=1002',
 'girg_deg_scaling_n=50000_deg=10_dim=2_ple=5.1_T=0.62_seed=1003',
 'girg_deg_scaling_n=50000_deg=10_dim=2_ple=5.1_T=0.62_seed=1004',
 'girg_deg_scaling_n=50000_deg=10_dim=2_ple=5.1_T=0.62_seed=1005',
 'girg_deg_scaling_n=50000_deg=10_dim=2_ple=5.1_T=0.62_seed=1006',
 'girg_deg_scaling_n=50000_deg=10_dim=2_ple=5.1_T=0.62_seed=1007',
 'girg_deg_scali

In [42]:
input_names_all = utils.graph_names

input_names_girg_deg_scaling = [
    name for name in input_names_all if name.startswith("girg_deg_scaling_")
]
# special graphs: high degree
input_names_gen_high_deg = [
    name
    for name in input_names_all
    if ("deg=20" in name or "m=500000" in name)
    and not name.startswith("girg_deg_scaling_")
]
# main data set
input_names = [
    name
    for name in input_names_all
    if not name.startswith("girg_deg_scaling_")
    and "deg=20" not in name
    and "m=500000" not in name
]
# girg part of main data set
input_names_girg = [
    name for name in input_names if name.startswith("girg_")
]
input_names_cl = [
    name for name in input_names if name.startswith("cl_")
]
input_names_er = [
    name for name in input_names if name.startswith("er_")
]

# all other graphs in input_names - real networks
input_names_real = list(set(input_names) - set(input_names_girg) - set(input_names_cl) - set(input_names_er))

print(f'input_names_all: {len(input_names_all)}')
print(f'input_names_girg_deg_scaling: {len(input_names_girg_deg_scaling)}')
print(f'input_names_gen_high_deg: {len(input_names_gen_high_deg)}')
print(f'input_names: {len(input_names)}')
print(f'input_names_girg: {len(input_names_girg)}')
print(f'input_names_cl: {len(input_names_cl)}')
print(f'input_names_er: {len(input_names_er)}')
print(f'input_names_real: {len(input_names_real)}')

input_names_all: 5487
input_names_girg_deg_scaling: 900
input_names_gen_high_deg: 555
input_names: 4032
input_names_girg: 1000
input_names_cl: 50
input_names_er: 5
input_names_real: 2977


In [43]:
input_names_all[:5]

['08blocks', '1138_bus', '130bit', '145bit', '162bit']

In [38]:
# temp df
df_nm = pd.DataFrame(temps, columns=['nodes', 'nodes_cl', 'edges', 'edges_cl'])
# df_nm

(df_nm['edges'] - df_nm['edges_cl']) / df_nm['edges']

0     0.027397
1     0.016461
2     0.022450
3     0.016354
4     0.016078
5     0.028004
6     0.031705
7     0.041100
8     0.001093
9    -0.001379
10   -0.001792
11    0.000097
12   -0.007215
13   -0.034130
14    0.000329
15    0.014349
16   -0.004680
17   -0.005034
18    0.019417
19    0.072771
20   -0.003095
21   -0.002642
22   -0.000940
23    0.166128
24    0.174451
25    0.017045
26    0.155172
27    0.001273
28    0.003016
29   -0.000505
30    0.003895
31    0.002849
32    0.010871
33    0.011648
34   -0.026549
35    0.000014
36    0.003913
37    0.076577
38   -0.166667
39    0.012698
dtype: float64

In [39]:
df_nm

nodes  nodes_cl   edges  edges_cl
0       38        38      73        71
1     1138      1138    1458      1434
2      584       584    6058      5922
3     1002      1002   11251     11067
4     3606      3606   37069     36473
5     7441      7441   82204     79902
6    13691     13691  154235    149345
7    24430     24430  299684    287367
8    27628     27628  207723    207496
9    54019     54019  472098    472749
10  101492    101492  772886    774271
11   28984     28984  288684    288656
12    4720      4720   13722     13821
13     494       494     586       606
14  110971    110971  741934    741690
15     662       662     906       893
16     685       685    1282      1288
17   23412     23412   97536     98027
18      94        94     103       101
19   99340     99340  427449    396343
20   98843     98843  239751    240493
21    6240      6240   18168     18216
22   60000     60000  350077    350406
23     804       804   46410     38700
24   10693     10693  639750    528145
25      33        33     528       519
26      57        57      58        49
27    1000      1000  450079    449506
28     125       125    6963      6942
29    2000      2000  999836   1000341
30     250       250   27984     27875
31     500       500  112332    112012
32    1916      1916  164934    163141
33     364       364   10474     10352
34      72        72     678       696
35   92183     92183  436445    436439
36    9187      9187   44211     44038
37      77        77     222       205
38       8         8      12        14
39      36        36     630       622

In [33]:
# temp df
df_nm = pd.DataFrame(temps, columns=['nodes', 'nodes_cl', 'edges', 'edges_cl'])
# df_nm

(df_nm['edges'] - df_nm['edges_cl']) / df_nm['edges']

0     0.027397
1     0.016461
2     0.022450
3     0.016354
4     0.016078
5     0.028004
6     0.031705
7     0.041100
8     0.001093
9    -0.001379
10   -0.001792
11    0.000097
12   -0.007215
13   -0.034130
14    0.000329
15    0.014349
16   -0.004680
17   -0.005034
18    0.019417
19    0.072771
dtype: float64

In [29]:
# temp df
df_nm = pd.DataFrame(temps, columns=['nodes', 'nodes_cl', 'edges', 'edges_cl'])
# df_nm

(df_nm['edges'] - df_nm['edges_cl']) / df_nm['edges']

0     0.041096
1     0.016461
2     0.022450
3     0.016354
4     0.016078
5     0.028004
6     0.031705
7     0.041100
8     0.001093
9    -0.001379
10   -0.001792
11    0.000097
12   -0.007215
13   -0.034130
14    0.000329
15    0.014349
16   -0.004680
17   -0.005034
18    0.019417
19    0.072771
dtype: float64

In [24]:
# temp df
df_nm = pd.DataFrame(temps, columns=['nodes', 'nodes_cl', 'edges', 'edges_cl'])
# df_nm

(df_nm['edges'] - df_nm['edges_cl']) / df_nm['edges']

0     0.123288
1     0.005487
2     0.000000
3     0.029953
4     0.010980
5     0.027079
6     0.030953
7     0.040826
8    -0.000318
9     0.000896
10    0.000320
11    0.002750
12    0.005976
13   -0.049488
14   -0.001150
15   -0.007726
16   -0.042122
17    0.005331
18    0.097087
19    0.071756
dtype: float64

In [23]:
# temp df
df_nm = pd.DataFrame(temps, columns=['nodes', 'nodes_cl', 'edges', 'edges_cl'])
# df_nm

(df_nm['edges'] - df_nm['edges_cl']) / df_nm['edges']

nodes  nodes_cl   edges  edges_cl
0       38        38      73        64
1     1138      1138    1458      1450
2      584       584    6058      6058
3     1002      1002   11251     10914
4     3606      3606   37069     36662
5     7441      7441   82204     79978
6    13691     13691  154235    149461
7    24430     24430  299684    287449
8    27628     27628  207723    207789
9    54019     54019  472098    471675
10  101492    101492  772886    772639
11   28984     28984  288684    287890
12    4720      4720   13722     13640
13     494       494     586       615
14  110971    110971  741934    742787
15     662       662     906       913
16     685       685    1282      1336
17   23412     23412   97536     97016
18      94        94     103        93
19   99340     99340  427449    396777

0     0.123288
1     0.005487
2     0.000000
3     0.029953
4     0.010980
5     0.027079
6     0.030953
7     0.040826
8    -0.000318
9     0.000896
10    0.000320
11    0.002750
12    0.005976
13   -0.049488
14   -0.001150
15   -0.007726
16   -0.042122
17    0.005331
18    0.097087
19    0.071756
dtype: float64